### ISSUE TITLE
Moodle integration: user with student role unable to see videos

### ISSUE THREAD

**Issue by andreacorleto** [teltek/PuMuKIT2-up2u-pr-bundle#16]
I have uploaded a video as a teacher, but user with a student role cannot see the video (see attached image). This is an already known issue (see [Trello board](https://trello.com/c/CAqXAGMj/24-personal-recorder-teltek)).
Test on the production platform https://learn.up2university.eu/
![screenshot-user-cannot-see-video](https://user-images.githubusercontent.com/36439670/52048925-cf77fc00-254c-11e9-9821-3cac268926e8.JPG)

**Comment by Alfro** [comment]
Hi, thanks for reporting the issue here.

As I mentioned on the Trello board, the access logs for this url shows that the wrong url is being accessed, which is most likely due to the filter not being correctly configured. The learn.test.up2university.eu instance seems to be working correctly, so it most likely is a configuration issue on the learn.up2university.eu instance.

@michzimny Could someone check the learn.up2university.eu configuration?

**Comment by michzimny** [comment]
> @michzimny Could someone check the learn.up2university.eu configuration?

@athird

**Comment by athird** [comment]
@Alfro Could you send me (by email, I guess?) what the configuration ought to be for the production instance (learn.up2university.eu), please? Currently it has the same configuration as the pedagogy instance (learn.test). Or, if I've already been sent those details at some point, could you remind me where they were sent and when, please, so that I can look them up?

**Comment by Alfro** [comment]
Sure @athird,

I'll write you an e-mail right now.

**Comment by andreacorleto** [comment]
Seems to be working now.

**Comment by Alfro** [comment]
Thanks @andreacorleto, I'll close the issue then.
